
q1=[
    [1,"world first computer ?","ENIAC ","Tata Institute of Fundamental Research Automatic Calculator (TIFRAC)f","Common Operating Machine ",1],
    [2,"2.how many generations of computers we have ?","one","ten","five",3],
    [3,'Who is the father of Computer science ?','stephen hawking','Charles Babbage','abdul kalam',2],
    [4,'In a computer, most processing takes place in _______?','mouse','.keyboard','CPU',3],
    [5,'Who is the father of personal computer?','Edward Robert','Charles Babbage','kevin mitnik',1],
    [6,'IBM stands for _______?','International Business Machines','Interpreted business machines','international barrier machines',1],
    [7,'.DOS stands for _______?','denial operating system','Disk Operating System','deniled operating system',2],
    [8,'Refresh Rate of monitor is measured in ?','Hertz','pixels','mm',1],
    [9,'Where are the CPU and memory located?','mouse','motherboard','processor',2],
    [10,'Full form of MAN?','motrologic area network','Metropolitan Area Network','Monition area network',2],
    [11,'In which year, the Microsoft company was founded?','1975','1972','1965',1],
    [12,'What are mouse and joystick?','input devices','prcessing devices','.output devices',1],
    [13,'What kind of memory is both static and non-volatile?','RAM','VRAM','ROM',3],
    [14,'Where does most data go first with in a computer memory hierarchy?','RAM','ROM','VRAM',1],
    [15,'When did arch rivals IBM and Apple Computers Inc. decide to join hands?','1991','1975','1968',1]
]
 

q2=[[1," Rectifiers are used to convert","Direct current to Alternating current ","Alternating current to Direct current","High voltage to low voltage ",2],
    [2," Intensity of sound at a point is __________ its distance from the source.","Directly proportional to","Inversely proportional to square of","Directly proportional to square of",2],
    [3,'Identify the vector quantity from the following','Heat',' Angular momentum','Time',2],
    [4,'Light travels at the fastest speed in','Glass',' Water','Vacuum',3],
    [5,' Metals are good conductors of electricity because','They contain free electrons','The atoms are lightly packed','All of the above',1],
    [6,'The velocity of sound in air (under normal condition) is',' 343 m/sec','320 m/sec','3,320 m/sec',1],
    [7,'If force is expressed in Newton and the distance in meter, then the work done is expressed in','Kg wt',' Joule','Watt',2],
    [8,'What is the function of a dynamo?','To convert mechanical energy into electrical energy','To convert heat energy into light energy','To convert electrical energy into mechanical energy',1],
    [9,'How much noise is produced when man breathes?',' 35 Decimal','10 Decimal','0.5 Decimal',2],
    [10,"Sound of frequency below 20 Hz is called",'Audio sounds',' Infrasonic',' Ultrasonic',2],
    [11,'Sound travels at the fastest speed in',' Steel','Water','Air',1],
    [12,'When cream is separated from milk','The density of milk increases',' The density of milk decreases','It becomes more viscous',1],
    [13,' Pick out the scalar quantity',' Force','Velocity','Pressure',3],
    [14,'Fathometer is used to measure',' Earthquakes',' Earthquakes','Sound intensity',2],
    [15,' Optical fibre works on the','Total internal reflection','Principle of refraction','Interference',1]]
q3=[[1,"3","ENIAC ","Tata Institute of Fundamental Research Automatic Calculator (TIFRAC)f","Common Operating Machine ",1],
    [2,"","one","ten","five",3],
    [3,'','stephen hawking','Charles Babbage','abdul kalam',2],
    [4,'','mouse','.keyboard','CPU',3],
    [5,'','Edward Robert','Charles Babbage','kevin mitnik',1],
    [6,'','International Business Machines','Interpreted business machines','international barrier machines',1],
    [7,'','denial operating system','Disk Operating System','deniled operating system',2],
    [8,'','Hertz','pixels','mm',1],
    [9,'','mouse','motherboard','processor',2],
    [10,"",'motrologic area network','Metropolitan Area Network','Monition area network',2],
    [11,'','1975','1972','1965',1],
    [12,'','input devices','prcessing devices','.output devices',1],
    [13,'','RAM','VRAM','ROM',3],
    [14,'','RAM','ROM','VRAM',1],
    [15,'','1991','1975','1968',1]]
q4=[[1,"4","ENIAC ","Tata Institute of Fundamental Research Automatic Calculator (TIFRAC)f","Common Operating Machine ",1],
    [2,"","one","ten","five",3],
    [3,'','stephen hawking','Charles Babbage','abdul kalam',2],
    [4,'','mouse','.keyboard','CPU',3],
    [5,'','Edward Robert','Charles Babbage','kevin mitnik',1],
    [6,'','International Business Machines','Interpreted business machines','international barrier machines',1],
    [7,'','denial operating system','Disk Operating System','deniled operating system',2],
    [8,'','Hertz','pixels','mm',1],
    [9,'','mouse','motherboard','processor',2],
    [10,"",'motrologic area network','Metropolitan Area Network','Monition area network',2],
    [11,'','1975','1972','1965',1],
    [12,'','input devices','prcessing devices','.output devices',1],
    [13,'','RAM','VRAM','ROM',3],
    [14,'','RAM','ROM','VRAM',1],
    [15,'','1991','1975','1968',1]]